<a href="https://colab.research.google.com/github/Suchithareddy05/23CSBTB39-40/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Hello, Python!')

Hello, Python!


In [ ]:
print(7+5)
print(10-3)
print(4*6)

12
7
24


In [ ]:
print("integer division:",17//4)
print("Modulo division:" ,17%4)

integer division: 4
Modulo division: 1


In [ ]:
a=3**4
print(a)

81


In [ ]:
print(2+3*4)
print((2+3)*4)

14
20


In [ ]:
a="Hello there"
print(a)

Hello there


In [ ]:
age=int(input())
years=100-age
print("The age left is:", years)

 54


The age left is: 46


In [ ]:
color=input("What is your favorite color")
print(color)

What is your favorite color blue


blue


In [ ]:
print("enter 1st integer")
a=int(input())
print("enter 2nd integer")
b=int(input())
c=a+b
print("Sum of the two integers is",c)

enter 1st integer


 5


enter 2nd integer


 6


Sum of the two integers is 11


In [ ]:
var=3.542
print(type(var))

<class 'float'>


In [ ]:
print("Hello"+" "+"World")

Hello World


In [ ]:
a="Python"
print(a[0],a[-1])

P n


In [ ]:
print(a[1:4])

yth


In [ ]:
x="Hello World"
print(x.count("l"))

3


In [ ]:
data="Python Programming"
print(data.lower())

python programming


In [ ]:
a="Java is widely used programmimg language"
z=a.replace("Java","Python")
print(z)

Python is widely used programmimg language


In [ ]:
"on" in "Python"

True

In [ ]:
name="Akash"
age=18
print("My name is",name,",I'm", age, "years old")

My name is Akash ,I'm 18 years old


In [ ]:
list=['orange','apple','melon','grapes','banana']
print(list)

['orange', 'apple', 'melon', 'grapes', 'banana']


In [ ]:
list.append('cherry')
print(list)

['orange', 'apple', 'melon', 'grapes', 'banana', 'cherry']


In [ ]:
list.sort()
print(list)

['apple', 'banana', 'cherry', 'grapes', 'melon', 'orange']


In [ ]:
del list[2]
print(list)

['apple', 'banana', 'grapes', 'melon', 'orange']


In [ ]:
print(list[0:3])

['apple', 'banana', 'grapes']


In [ ]:
colors=('red','blue','green')
print(colors)

('red', 'blue', 'green')


In [ ]:
colors[1]='pink'
print(colors)

TypeError: 'tuple' object does not support item assignment

In [ ]:
c1,c2,c3=colors
print(c1,c2,c3)

red blue green


In [ ]:
dict={'name':'siri','age':18, 'city':'warangal'}
print(dict)

{'name': 'siri', 'age': 18, 'city': 'warangal'}


In [ ]:
dict['country']='india'
print(dict)

{'name': 'siri', 'age': 18, 'city': 'warangal', 'country': 'india'}


In [ ]:
print(dict.keys())
print(dict.values())

dict_keys(['name', 'age', 'city', 'country'])
dict_values(['siri', 18, 'warangal', 'india'])


In [ ]:
'age' in dict

True

In [ ]:
a={10,20,30,40,50}
b={20,40,60,70,90}
print(a)

{50, 20, 40, 10, 30}


In [ ]:
union=a|b
inter=a&b
print("union:",union)
print("intersection:",inter)

union: {70, 40, 10, 50, 20, 90, 60, 30}
intersection: {40, 20}


In [ ]:
n=int(input())
if (n%2==0):
    print("even")
else:
    print("odd")

 56


even


In [ ]:
marks=int(input("enter the marks scored"))
if marks>90:
    grade='A'
elif marks>80 or marks<=90:
    grade='B'
elif marks>70 or marks<=80:
    grade='C'
elif marks>60 or marks<=70:
    grade='D'
elif marks>50 or marks<=60:
    grade='E'
else:
    grade='Fail'
print("grade: ",grade)

enter the marks scored 98


grade:  A


In [ ]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(1,6):
    print(i,"*",i,"=",i*i)

1 * 1 = 1
2 * 2 = 4
3 * 3 = 9
4 * 4 = 16
5 * 5 = 25


In [ ]:
n=10
while n>=1:
    print(n)
    n-=1

10
9
8
7
6
5
4
3
2
1


In [ ]:
n=2
sum=0
while n<=100:
    sum+=n
    n+=2
print(sum)


2550


In [ ]:
var=input("enter the string")
vowels='a e i o u'
count=0
for i in var:
    if i in vowels:
        count+=1
print(count)

enter the string hey


1


In [ ]:
def sum(a,b):
    c=a+b
    return c

In [ ]:
def sum(a=5,b=10):
    c=a+b
    return c
print(c)

11


In [ ]:
def summ(*args):
    return sum(args)

In [ ]:
def square_cube(n):
    return n**2 ,n**3
n=int(input())
print(n**2 ,n**3)

 5


25 125


In [ ]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        fact=n * factorial(n - 1)
        return fact
n=int(input())
print(factorial(n))

 3


6


In [ ]:
filename=r"C:\Users\samee\OneDrive\Desktop\extensions.txt"
with open(filename) as file_object:
    lines=file_object.readlines()

for line in lines:
    print(line)

*extensions*

vscode-icons

dev containers

angular language service

docker

GitHub actions

hide comments

jellyfish(theme)

live sass compiler

live server

one dark pro(theme)

oracle sql developer extension

prettier-code formatter

pylance

python

python debugger

rainbow CSV

vue-official


In [ ]:
with open(filename, 'r') as file:
    lines = file.readlines()
    print("Number of lines:", len(lines))


Number of lines: 18


In [ ]:
with open(filename, 'r') as file:
    words=0
    for line in file:
        words+=len(line.split())
print("Number of words:", words)

Number of words: 34


In [ ]:
with open(filename,'w') as file:
    file.write("Hello, this is a file containing multiple lines")

In [ ]:
with open(filename,'a') as file:
    file.write("This file is created by sameera")

In [ ]:
a=int(input("enter a value"))
b=int(input("enter b value"))
try:
    result=a/b
    print(result)
except ZeroDivisionError:
    print("Division by zero is not allowed.")

enter a value 5
enter b value 0


Division by zero is not allowed.


In [ ]:
try:
    with open("sameera",'r')as file:
        content=file.read()
except FileNotFoundError:
    print("File not Found")

File not Found


In [ ]:
try:
    a=int(input())
    if a<0:
        print("input is negative")
except valueerror:
    print(a)


 -9


input is negative


In [ ]:
try:
    file=open(r"C:\Users\samee\OneDrive\Desktop\extensions.txt",'r')
    content=file.read()
    print(content)
except FileNotFoundError:
    print("Error")
finally:
    file.close()
    print("file has been closed")

Hello, this is a file containing multiple linesThis file is created by sameera
file has been closed


In [ ]:
math.sqrt(16)

4.0

In [ ]:
n=int(input())
sine=math.sin(math.radians(n))
cosine=math.cos(math.radians(n))
print("sin",n,"=",sine)
print("cos",n,"=",cosine)

 90


sin 90 = 1.0
cos 90 = 6.123233995736766e-17


In [ ]:
for i in range(10):
    print(random.randint(1,100))

66
49
41
23
50
36
68
77
46
1


In [ ]:
import numpy as np
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
matrix=np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
print(arr[:9].reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr1=np.array([5,7,6,2,9])
arr2=np.array([12,23,34,25,26])
sumarr=arr1+arr2
diff=arr1-arr2
mul=arr1*arr2
print(sumarr, "\n",diff, "\n",mul)

[17 30 40 27 35] 
 [ -7 -16 -28 -23 -17] 
 [ 60 161 204  50 234]


In [ ]:
import numpy as np
array=np.array([5,6,7,9])
print("max:",max(array))
print("min:",min(array))
print("mean:",array.mean())

max: 9
min: 5
mean: 6.75


In [ ]:
print(arr1[:3])

[5 7 6]


In [ ]:
import pandas as pd
data=[10,20,30,40,50]
series=pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
dict={"name":["anu","ali","chintu"],
      "age":[25,30,61]}
df=pd.DataFrame(dict)
print(df)

     name  age
0     anu   25
1     ali   30
2  chintu   61


In [ ]:
csv_f=pd.read_csv(r"C:\Users\samee\OneDrive\Desktop\academics\2-1\AIML\student.csv")
print(csv_f)

    SID      name course  contact number
0  2121       ant    CSE             122
1  2122        at    ECE             123
2  2123       cat    CSE             124
3  2124       dog    ECE             125
4  2125  elephant    EEE             126
5  2126      fish    EEE             127
6  2127      goat    CSE             128
7  2128     horse    ECE             129


In [ ]:
print(csv_f.head())

    SID      name course  contact number
0  2121       ant    CSE             122
1  2122        at    ECE             123
2  2123       cat    CSE             124
3  2124       dog    ECE             125
4  2125  elephant    EEE             126


In [ ]:
mean=df['SID'].mean()
print(mean)

KeyError: 'SID'