<a href="https://colab.research.google.com/github/Suchithareddy05/23CSBTB39-40/blob/main/Assignment_2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
m = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
n = m.shape[0]
for i in range(n):
    for j in range(i + 1, n):
        m[i, j], m[j, i] = m[j, i], m[i, j]
for i in range(n):
    m[i] = m[i][::-1]
print(m)

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [ ]:
import numpy as np
a = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
flattened = []
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[2]):
            flattened.append(a[i][j][k])
flattened_array = np.array(flattened)
print(flattened_array)


[1 2 3 4 5 6 7 8]


In [ ]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])

k = 3
n = matrix.shape[0]

if n % k != 0:
    print("Matrix cannot split into parts.")

part_size = n // k
parts = []

for i in range(0, n, part_size):
    parts.append(matrix[i:i + part_size])

for idx, part in enumerate(parts):
    print(f"Part {idx + 1}:\n{part}\n")


Part 1:
[[1 2 3]
 [4 5 6]]

Part 2:
[[ 7  8  9]
 [10 11 12]]

Part 3:
[[13 14 15]
 [16 17 18]]



In [ ]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
matrix = [row[::-1] for row in matrix]
for row in matrix:
    print(row)


[3, 2, 1]
[6, 5, 4]
[9, 8, 7]


In [ ]:
n = 8
matrix = [[(i + j) % 2 for j in range(n)] for i in range(n)]
for row in matrix:
    print(row)

[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]


In [ ]:
a = [1, 2, 3]
b = [0, 1, 0.5]
n = len(a)
m = len(b)
result = [0] * (n + m - 1)
for i in range(n):
    for j in range(m):
        result[i + j] += a[i] * b[j]
print(result)

[0, 1, 2.5, 4.0, 1.5]


In [ ]:
import numpy as np
arr = np.array([
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, 9]
])
row_means = np.nanmean(arr, axis=1)
for i in range(arr.shape[0]):
    arr[i][np.isnan(arr[i])] = row_means[i]
print(arr)

[[1.  2.  1.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [ ]:
import numpy as np
first_col = np.array([1, 2, 3, 4])
first_row = np.array([1, 5, 6, 7])
i = np.arange(len(first_col))[:, None]
j = np.arange(len(first_row))
a = first_col[i - j]

print(a)


[[1 4 3 2]
 [2 1 4 3]
 [3 2 1 4]
 [4 3 2 1]]


In [ ]:
import numpy as np

size = 5
sigma = 1.0

ax = np.arange(-(size // 2), size // 2 + 1)
xx, yy = np.meshgrid(ax, ax)
kernel = np.exp(-(xx**2 + yy**2) / (2.0 * sigma**2))
kernel = kernel / np.sum(kernel)

print(kernel)


[[0.00296902 0.01330621 0.02193823 0.01330621 0.00296902]
 [0.01330621 0.0596343  0.09832033 0.0596343  0.01330621]
 [0.02193823 0.09832033 0.16210282 0.09832033 0.02193823]
 [0.01330621 0.0596343  0.09832033 0.0596343  0.01330621]
 [0.00296902 0.01330621 0.02193823 0.01330621 0.00296902]]


In [ ]:
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9]
])
unique_rows = np.unique(arr, axis=0)
print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A_exp = A[:, :, None]
B_exp = B.T[None, :, :]
result = np.sum(A_exp * B_exp, axis=1)

print(result)


[[17 23]
 [39 53]]


In [ ]:
arr = np.array([[1, 2], [3, 4]])
k = 1
padded = np.pad(arr, pad_width=k, mode='constant', constant_values=0)
print(padded)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In [ ]:
def custom_reshape(arr, new_shape):
    if np.prod(arr.shape) != np.prod(new_shape):
        raise ValueError("Incompatible shapes for reshape")
    return np.array(arr).flatten()[:np.prod(new_shape)].reshape(new_shape)

arr = np.array([[1, 2], [3, 4]])
reshaped = custom_reshape(arr, (4,))
print(reshaped)


[1 2 3 4]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
n = arr.shape[0]
mask = np.tri(n, dtype=int)
cumsum = np.dot(mask, arr)

print(cumsum)


[ 1  3  6 10]


In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
main_diag = np.diag(matrix)
anti_diag = np.diag(np.fliplr(matrix))
print("Diagonal:", main_diag)
print("Anti-diagonal:", anti_diag)

Diagonal: [1 5 9]
Anti-diagonal: [3 5 7]


In [ ]:
arr = np.array([[3, 1], [4, 2]])
sorted_rows = np.sort(arr, axis=1)
sorted_cols = np.sort(sorted_rows, axis=0)
print(sorted_cols)

[[1 3]
 [2 4]]


In [ ]:
arr = np.random.randint(0, 10, size=(1000, 1000))
vals, counts = np.unique(arr, return_counts=True)
most_freq = vals[np.argmax(counts)]
print(most_freq)

2


In [ ]:
arr = np.random.rand(2, 3, 4)
permuted = arr.swapaxes(0, 2).swapaxes(1, 2)
print(permuted.shape)

(4, 2, 3)


In [ ]:
arr = np.array([
    [0, 0, 1, 1],
    [0, 0, 0, 1]
])
flat = arr.flatten()
changes = np.diff(flat, prepend=flat[0])
positions = np.where(changes != 0)[0]
lengths = np.diff(np.append(positions, len(flat)))
values = flat[positions]
rle = list(zip(values, lengths))
print(rle)

[(1, 2), (0, 3), (1, 1)]


In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
k = 1
shifted = np.vstack((arr[-k:], arr[:-k]))
print(shifted)

In [ ]:
import numpy as np
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.dot(np.linalg.inv(A), b)
print(x)


[2. 3.]


In [ ]:
Q, R = np.linalg.qr(np.random.randn(4, 4))
print(Q)
print(np.dot(Q, Q.T))

[[-0.40873096  0.8035724   0.38744358 -0.19260809]
 [-0.71765908 -0.50264454  0.410768    0.25215782]
 [-0.3907947  -0.18636558 -0.42177319 -0.79665221]
 [-0.40642828  0.25862664 -0.70941138  0.51445487]]
[[ 1.00000000e+00  1.66533454e-16 -5.63785130e-17 -8.32667268e-17]
 [ 1.66533454e-16  1.00000000e+00  2.77555756e-17  6.09321621e-17]
 [-5.63785130e-17  2.77555756e-17  1.00000000e+00 -5.55111512e-17]
 [-8.32667268e-17  6.09321621e-17 -5.55111512e-17  1.00000000e+00]]


In [ ]:
A = np.array([[4, 2], [1, 3]])
vals, vecs = np.linalg.eig(A)
for i in range(len(vals)):
    left = np.dot(A, vecs[:, i])
    right = vals[i] * vecs[:, i]
    print(np.allclose(left, right))

True
True


In [ ]:
A = np.array([[1., 1., 0.], [1., 0., 1.], [0., 1., 1.]])
m, n = A.shape
Q = np.zeros((m, n))
R = np.zeros((n, n))
for k in range(n):
    u = A[:, k].copy()
    for j in range(k):
        R[j, k] = np.dot(Q[:, j], A[:, k])
        u -= R[j, k] * Q[:, j]
    R[k, k] = np.linalg.norm(u)
    Q[:, k] = u / R[k, k]
print(Q)
print(R)

[[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]
[[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]


In [ ]:
A = np.array([[1, 2], [3, 4]])
s = np.linalg.svd(A, compute_uv=False)
c = s[0] / s[-1]
print(c)

14.933034373659265


In [ ]:
def is_pos_def(M):
    try:
        np.linalg.cholesky(M)
        return True
    except np.linalg.LinAlgError:
        return False

M = np.array([[2, -1], [-1, 2]])
print(is_pos_def(M))


True


In [ ]:
X = np.random.randn(100, 5)
X_centered = X - X.mean(axis=0)
U, S, VT = np.linalg.svd(X_centered, full_matrices=False)
PCs = np.dot(X_centered, VT.T)
print(PCs)


[[ 5.14190701e-01  6.12087376e-01  7.93146809e-01 -1.14468006e+00
  -9.61199183e-01]
 [ 1.34900202e+00  2.95256554e-01 -1.06501237e+00  1.23618467e-01
   9.10953653e-01]
 [ 7.18622616e-01 -1.69732488e+00 -6.25225263e-01 -1.17567997e+00
  -1.79433230e+00]
 [-5.75327075e-01  1.97440416e-01 -1.44619009e+00  7.21378273e-01
  -3.60600098e-01]
 [-8.28950540e-01  1.43606866e-01  2.58770962e-02 -7.84721067e-01
  -2.00269196e+00]
 [-1.39879842e+00  1.41758101e+00 -7.27966224e-01 -9.40617807e-01
  -5.63259471e-01]
 [ 3.47779211e-01 -1.90961419e+00  2.76926674e-01 -4.40433419e-01
  -3.28276994e-01]
 [-2.14537498e+00 -1.94662353e-01 -8.36518589e-01 -4.75318136e-01
   6.05684107e-01]
 [ 1.09386710e+00  8.73768765e-01  1.29599484e+00  6.48147629e-01
  -1.97562884e-01]
 [ 2.17069100e+00 -6.28477769e-03 -5.49164545e-01 -1.34549951e-01
  -5.50008014e-01]
 [ 2.34979682e-01 -1.27723146e+00  3.71736049e-01 -1.12615546e+00
   1.58246734e+00]
 [-8.54415266e-01 -1.53139841e-01  6.76336276e-01  1.06333035e+00

In [ ]:
X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([1, 2, 3])
beta = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), y)
print(beta)


[8.8817842e-16 1.0000000e+00]


In [ ]:
data = np.random.randn(100, 3)
corr = np.corrcoef(data, rowvar=False)
print(corr)


[[ 1.         -0.22233999  0.24476543]
 [-0.22233999  1.         -0.12824962]
 [ 0.24476543 -0.12824962  1.        ]]


In [ ]:
def generate_matrix_with_singular_values(singular_values, m, n):
    r = len(singular_values)
    U, _ = np.linalg.qr(np.random.randn(m, m))
    V, _ = np.linalg.qr(np.random.randn(n, n))
    Sigma = np.zeros((m, n))
    np.fill_diagonal(Sigma, singular_values)
    US = np.dot(U, Sigma)
    A = np.dot(US, V.T)
    return A

singular_vals = [5, 3, 1]
A = generate_matrix_with_singular_values(singular_vals, 5, 4)
print(np.linalg.svd(A, compute_uv=False)[:len(singular_vals)])


[5. 5. 3.]


In [ ]:
import numpy as np

def multivariate_normal_samples(mean, cov, n_samples):
    L = np.linalg.cholesky(cov)
    z = np.random.randn(n_samples, len(mean))
    samples = np.dot(z, L.T) + mean
    return samples

mean = np.array([0, 0])
cov = np.array([[1, 0.5], [0.5, 1]])
samples = multivariate_normal_samples(mean, cov, 5)
print(samples)


[[-0.03259105  0.64182479]
 [-0.51078195 -0.29145681]
 [ 0.94193292  0.40405579]
 [-0.48067408 -0.62537758]
 [ 1.22793476 -0.70461542]]


In [ ]:
def mahalanobis(x, y, cov_inv):
    diff = x - y
    return np.sqrt(np.dot(np.dot(diff.T, cov_inv), diff))

x = np.array([1, 2])
y = np.array([2, 3])
cov = np.array([[2, 0.5], [0.5, 1]])
cov_inv = np.linalg.inv(cov)
dist = mahalanobis(x, y, cov_inv)
print(dist)


1.0690449676496976


In [ ]:
def kmeans(X, k, max_iter=100):
    n_samples, n_features = X.shape
    centroids = X[np.random.choice(n_samples, k, replace=False)]
    for _ in range(max_iter):
        distances = np.array([[np.linalg.norm(x - c) for c in centroids] for x in X])
        labels = np.argmin(distances, axis=1)
        new_centroids = np.array([X[labels == i].mean(axis=0) for i in range(k)])
        if np.allclose(centroids, new_centroids):
            break
        centroids = new_centroids
    return labels, centroids

X = np.random.randn(10, 2)
labels, centroids = kmeans(X, 3)
print(labels)
print(centroids)


[1 2 1 0 0 1 0 1 0 0]
[[-0.47634361  0.23678546]
 [ 0.38811667 -1.33890855]
 [ 0.96222705  0.86630574]]


In [ ]:
def normalize_columns(M):
    min_col = M.min(axis=0)
    max_col = M.max(axis=0)
    return (M - min_col) / (max_col - min_col)

M = np.array([[1, 2], [3, 4]])
normalized = normalize_columns(M)
print(normalized)


[[0. 0.]
 [1. 1.]]


In [ ]:
def mean_filter_3x3(M):
    padded = np.pad(M, 1, mode='constant', constant_values=0)
    filtered = np.zeros_like(M, dtype=float)
    rows, cols = M.shape
    for i in range(rows):
        for j in range(cols):
            neighborhood = padded[i:i+3, j:j+3]
            filtered[i, j] = neighborhood.mean()
    return filtered

M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
filtered = mean_filter_3x3(M)
print(filtered)


[[1.33333333 2.33333333 1.77777778]
 [3.         5.         3.66666667]
 [2.66666667 4.33333333 3.11111111]]


In [ ]:
def brownian_motion(n_steps, dim=1):
    steps = np.random.randn(n_steps, dim)
    return np.cumsum(steps, axis=0)

bm = brownian_motion(10)
print(bm)


[[-1.19478804]
 [ 0.11315216]
 [ 2.36477033]
 [ 1.60859872]
 [ 1.83897971]
 [ 2.24751127]
 [ 3.61899116]
 [ 3.13823508]
 [ 2.28994874]
 [ 0.74386199]]


In [ ]:
def kalman_update(x_prior, P_prior, z, H, R):
    y = z - np.dot(H, x_prior)              # Innovation
    S = np.dot(H, np.dot(P_prior, H.T)) + R # Innovation covariance
    K = np.dot(P_prior, np.dot(H.T, np.linalg.inv(S)))  # Kalman gain
    x_post = x_prior + np.dot(K, y)
    I = np.eye(len(x_prior))
    P_post = np.dot(I - np.dot(K, H), P_prior)
    return x_post, P_post

x_prior = np.array([0, 0])
P_prior = np.eye(2)
z = np.array([1, 1])
H = np.eye(2)
R = np.eye(2) * 0.1
x_post, P_post = kalman_update(x_prior, P_prior, z, H, R)
print(x_post)
print(P_post)


[0.90909091 0.90909091]
[[0.09090909 0.        ]
 [0.         0.09090909]]


In [ ]:
def determinant(A):
    A = A.astype(float)
    n = A.shape[0]
    det = 1
    for i in range(n):
        max_row = i + np.argmax(abs(A[i:, i]))
        if i != max_row:
            A[[i, max_row]] = A[[max_row, i]]
            det *= -1
        det *= A[i, i]
        if A[i, i] == 0:
            return 0
        for j in range(i+1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
    return det

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
print(determinant(A))


-2.9999999999999982


In [ ]:
def is_symmetric(M):
    return np.allclose(M, M.T)

M1 = np.array([[1, 2], [2, 1]])
M2 = np.array([[1, 0], [2, 1]])
print(is_symmetric(M1))  # True
print(is_symmetric(M2))  # False


True
False


In [ ]:
import numpy as np
from scipy.optimize import minimize

def noisy_func(x):
    noise = np.random.normal(0, 0.1)
    return np.sin(3*x) + np.cos(5*x) + noise

res = minimize(noisy_func, x0=0, method='Nelder-Mead')
print(res.x, res.fun)


[4.68750298e-05] 0.7099532558731402


In [ ]:
def f(x):
    return x**4 - 3*x**3 + 2

def grad_f(x):
    return 4*x**3 - 9*x**2

x = 0.0
lr = 0.01
for _ in range(1000):
    x -= lr * grad_f(x)
print(x, f(x))


0.0 2.0


In [ ]:
from scipy.optimize import fsolve

def system(vars):
    x, y = vars
    return [x**2 + y**2 - 4, x - y - 1]

sol = fsolve(system, [1, 1])
print(sol)


[1.82287566 0.82287566]


In [ ]:
from scipy.optimize import curve_fit

def model(x, a, b):
    return a * np.exp(b * x)

xdata = np.linspace(0, 4, 50)
ydata = model(xdata, 2.5, 1.3) + 0.5 * np.random.normal(size=xdata.size)

params, _ = curve_fit(model, xdata, ydata)
print(params)


[2.49980922 1.30016428]


In [ ]:
from scipy.optimize import basinhopping

def black_box(x):
    return -((x[0]-1)**2 + (x[1]-2)**2)  # negative for maximization

bounds = [(-5, 5), (-5, 5)]

class Bounds:
    def __init__(self, xmin, xmax):
        self.xmin = np.array(xmin)
        self.xmax = np.array(xmax)
    def __call__(self, **kwargs):
        x = kwargs["x_new"]
        return np.all(x >= self.xmin) and np.all(x <= self.xmax)

bounds_checker = Bounds([-5, -5], [5, 5])

res = basinhopping(black_box, x0=[0,0], minimizer_kwargs={"method": "L-BFGS-B", "bounds": bounds}, accept_test=bounds_checker)
print(res.x, -res.fun)


[-5. -5.] 85.0


In [ ]:
def rosenbrock(x):
    return (1 - x[0])**2 + 100*(x[1] - x[0]**2)**2

res = minimize(rosenbrock, x0=[0,0], method='BFGS')
print(res.x, res.fun)


[0.99999467 0.99998932] 2.8439990629105454e-11


In [ ]:
import numpy as np
from scipy.special import expit  # sigmoid
from scipy.optimize import minimize

X = np.array([[1, 2], [1, 3], [1, 4], [1, 5]])  # including bias term
y = np.array([0, 0, 1, 1])

def neg_log_likelihood(beta):
    z = np.dot(X, beta)  # avoid @ if required
    p = expit(z)
    return -np.sum(y * np.log(p + 1e-9) + (1 - y) * np.log(1 - p + 1e-9))

beta_init = np.zeros(X.shape[1])
res = minimize(neg_log_likelihood, beta_init, method='BFGS')

print("Estimated coefficients:", res.x)



Estimated coefficients: [-90.8042913   25.88980191]


In [ ]:
from scipy.optimize import LinearConstraint

def func(x):
    return (x[0]-1)**2 + (x[1]-2.5)**2

bounds = [(0, None), (0, None)]
linear_constraint = LinearConstraint([[1, 2]], [1], [2])

res = minimize(func, [2, 0], method='trust-constr', bounds=bounds, constraints=[linear_constraint])
print(res.x, res.fun)


[0.20001059 0.89999271] 3.2000064005261426


In [ ]:
methods = ['Nelder-Mead', 'BFGS', 'CG', 'Powell']
results = {}

def f(x):
    return (x-3)**2 + 1

for method in methods:
    res = minimize(f, x0=0, method=method)
    results[method] = (res.x, res.fun, res.nit)

print(results)


{'Nelder-Mead': (array([3.]), 1.0, 28), 'BFGS': (array([3.00000003]), 1.0000000000000009, 2), 'CG': (array([3.0000002]), 1.0000000000000384, 1), 'Powell': (array([3.]), array(1.), 2)}


In [ ]:
def f(x):
    return (x - 2)**2 + 3

res = minimize(f, x0=0, jac=None, method='BFGS')
print(res.x, res.fun)


[1.99999999] 3.0
